// flow-typed signature: 21e79faa87f9882eb0d2ca8ca8223a6b
// flow-typed version: <<STUB>>/eslint-config-nhardy_v^0.2.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-nhardy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-nhardy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-nhardy/dev' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/dist/dev' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/dist/index' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/dist/lib/globals' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/dist/tests' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/src/dev' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/src/index' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/src/lib/globals' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/src/tests' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-nhardy/dev.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/dev'>;
}
declare module 'eslint-config-nhardy/dist/dev.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/dist/dev'>;
}
declare module 'eslint-config-nhardy/dist/index.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/dist/index'>;
}
declare module 'eslint-config-nhardy/dist/lib/globals.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/dist/lib/globals'>;
}
declare module 'eslint-config-nhardy/dist/tests.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/dist/tests'>;
}
declare module 'eslint-config-nhardy/index' {
  declare module.exports: $Exports<'eslint-config-nhardy'>;
}
declare module 'eslint-config-nhardy/index.js' {
  declare module.exports: $Exports<'eslint-config-nhardy'>;
}
declare module 'eslint-config-nhardy/src/dev.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/src/dev'>;
}
declare module 'eslint-config-nhardy/src/index.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/src/index'>;
}
declare module 'eslint-config-nhardy/src/lib/globals.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/src/lib/globals'>;
}
declare module 'eslint-config-nhardy/src/tests.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/src/tests'>;
}
declare module 'eslint-config-nhardy/tests.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/tests'>;
}
