// flow-typed signature: a9d757b55b9c89521b8372ea63a38e12
// flow-typed version: <<STUB>>/eslint-config-nhardy_v^0.3.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-nhardy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-nhardy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-nhardy/dev' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/dist/dev' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/dist/index' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/dist/lib/globals' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/dist/tests' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/dist/withFlow' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/babel-plugin-add-module-exports_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-es2015-node_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-es2016_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-es2017_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/eslint-plugin-mocha_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/src/dev' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/src/index' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/src/lib/globals' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/src/tests' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/src/withFlow' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/tests' {
  declare module.exports: any;
}

declare module 'eslint-config-nhardy/withFlow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-nhardy/dev.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/dev'>;
}
declare module 'eslint-config-nhardy/dist/dev.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/dist/dev'>;
}
declare module 'eslint-config-nhardy/dist/index.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/dist/index'>;
}
declare module 'eslint-config-nhardy/dist/lib/globals.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/dist/lib/globals'>;
}
declare module 'eslint-config-nhardy/dist/tests.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/dist/tests'>;
}
declare module 'eslint-config-nhardy/dist/withFlow.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/dist/withFlow'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/babel-plugin-add-module-exports_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/babel-plugin-add-module-exports_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/babel-plugin-transform-object-rest-spread_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-es2015-node_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/babel-preset-es2015-node_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-es2016_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/babel-preset-es2016_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-es2017_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/babel-preset-es2017_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/eslint-plugin-mocha_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/eslint-plugin-mocha_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'eslint-config-nhardy/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'eslint-config-nhardy/index' {
  declare module.exports: $Exports<'eslint-config-nhardy'>;
}
declare module 'eslint-config-nhardy/index.js' {
  declare module.exports: $Exports<'eslint-config-nhardy'>;
}
declare module 'eslint-config-nhardy/src/dev.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/src/dev'>;
}
declare module 'eslint-config-nhardy/src/index.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/src/index'>;
}
declare module 'eslint-config-nhardy/src/lib/globals.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/src/lib/globals'>;
}
declare module 'eslint-config-nhardy/src/tests.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/src/tests'>;
}
declare module 'eslint-config-nhardy/src/withFlow.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/src/withFlow'>;
}
declare module 'eslint-config-nhardy/tests.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/tests'>;
}
declare module 'eslint-config-nhardy/withFlow.js' {
  declare module.exports: $Exports<'eslint-config-nhardy/withFlow'>;
}
