// flow-typed signature: 746f2f17a8b557787f3c5a4032a1e393
// flow-typed version: <<STUB>>/react-display-name_v^0.2.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-display-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-display-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-display-name/lib/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-display-name/spec/getDislplayNameSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-display-name/lib/getDisplayName.js' {
  declare module.exports: $Exports<'react-display-name/lib/getDisplayName'>;
}
declare module 'react-display-name/spec/getDislplayNameSpec.js' {
  declare module.exports: $Exports<'react-display-name/spec/getDislplayNameSpec'>;
}
