// flow-typed signature: f59654fbd0566c0a8de4dbdce8db047b
// flow-typed version: <<STUB>>/redux-scripts-manager_v^0.2.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-scripts-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-scripts-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-scripts-manager/dist/actions' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/dist/constants' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/dist/index' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/dist/listeners' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/dist/manager' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/dist/reducer' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/src/actions' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/src/constants' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/src/index' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/src/listeners' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/src/manager' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/src/reducer' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/test/setup' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/test/unit/actions.spec' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/test/unit/index.spec' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/test/unit/listeners.spec' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/test/unit/manager.spec' {
  declare module.exports: any;
}

declare module 'redux-scripts-manager/test/unit/reducer.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-scripts-manager/dist/actions.js' {
  declare module.exports: $Exports<'redux-scripts-manager/dist/actions'>;
}
declare module 'redux-scripts-manager/dist/constants.js' {
  declare module.exports: $Exports<'redux-scripts-manager/dist/constants'>;
}
declare module 'redux-scripts-manager/dist/index.js' {
  declare module.exports: $Exports<'redux-scripts-manager/dist/index'>;
}
declare module 'redux-scripts-manager/dist/listeners.js' {
  declare module.exports: $Exports<'redux-scripts-manager/dist/listeners'>;
}
declare module 'redux-scripts-manager/dist/manager.js' {
  declare module.exports: $Exports<'redux-scripts-manager/dist/manager'>;
}
declare module 'redux-scripts-manager/dist/reducer.js' {
  declare module.exports: $Exports<'redux-scripts-manager/dist/reducer'>;
}
declare module 'redux-scripts-manager/index' {
  declare module.exports: $Exports<'redux-scripts-manager'>;
}
declare module 'redux-scripts-manager/index.js' {
  declare module.exports: $Exports<'redux-scripts-manager'>;
}
declare module 'redux-scripts-manager/src/actions.js' {
  declare module.exports: $Exports<'redux-scripts-manager/src/actions'>;
}
declare module 'redux-scripts-manager/src/constants.js' {
  declare module.exports: $Exports<'redux-scripts-manager/src/constants'>;
}
declare module 'redux-scripts-manager/src/index.js' {
  declare module.exports: $Exports<'redux-scripts-manager/src/index'>;
}
declare module 'redux-scripts-manager/src/listeners.js' {
  declare module.exports: $Exports<'redux-scripts-manager/src/listeners'>;
}
declare module 'redux-scripts-manager/src/manager.js' {
  declare module.exports: $Exports<'redux-scripts-manager/src/manager'>;
}
declare module 'redux-scripts-manager/src/reducer.js' {
  declare module.exports: $Exports<'redux-scripts-manager/src/reducer'>;
}
declare module 'redux-scripts-manager/test/setup.js' {
  declare module.exports: $Exports<'redux-scripts-manager/test/setup'>;
}
declare module 'redux-scripts-manager/test/unit/actions.spec.js' {
  declare module.exports: $Exports<'redux-scripts-manager/test/unit/actions.spec'>;
}
declare module 'redux-scripts-manager/test/unit/index.spec.js' {
  declare module.exports: $Exports<'redux-scripts-manager/test/unit/index.spec'>;
}
declare module 'redux-scripts-manager/test/unit/listeners.spec.js' {
  declare module.exports: $Exports<'redux-scripts-manager/test/unit/listeners.spec'>;
}
declare module 'redux-scripts-manager/test/unit/manager.spec.js' {
  declare module.exports: $Exports<'redux-scripts-manager/test/unit/manager.spec'>;
}
declare module 'redux-scripts-manager/test/unit/reducer.spec.js' {
  declare module.exports: $Exports<'redux-scripts-manager/test/unit/reducer.spec'>;
}
