// flow-typed signature: a13de07fb8e9fee48cc0b09255d7c926
// flow-typed version: <<STUB>>/ua-parser-js_v^0.7.12/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ua-parser-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ua-parser-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ua-parser-js/dist/ua-parser.min' {
  declare module.exports: any;
}

declare module 'ua-parser-js/dist/ua-parser.pack' {
  declare module.exports: any;
}

declare module 'ua-parser-js/package' {
  declare module.exports: any;
}

declare module 'ua-parser-js/src/ua-parser' {
  declare module.exports: any;
}

declare module 'ua-parser-js/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ua-parser-js/dist/ua-parser.min.js' {
  declare module.exports: $Exports<'ua-parser-js/dist/ua-parser.min'>;
}
declare module 'ua-parser-js/dist/ua-parser.pack.js' {
  declare module.exports: $Exports<'ua-parser-js/dist/ua-parser.pack'>;
}
declare module 'ua-parser-js/package.js' {
  declare module.exports: $Exports<'ua-parser-js/package'>;
}
declare module 'ua-parser-js/src/ua-parser.js' {
  declare module.exports: $Exports<'ua-parser-js/src/ua-parser'>;
}
declare module 'ua-parser-js/test/test.js' {
  declare module.exports: $Exports<'ua-parser-js/test/test'>;
}
