// flow-typed signature: c9bc3f94f56ca993332b4b27cdef0e1a
// flow-typed version: <<STUB>>/webpack-node-externals_v^1.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-node-externals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-node-externals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-node-externals/index' {
  declare module.exports: $Exports<'webpack-node-externals'>;
}
declare module 'webpack-node-externals/index.js' {
  declare module.exports: $Exports<'webpack-node-externals'>;
}
